### ISSUE TITLE
Choc spacing

### ISSUE THREAD

**Issue by nanpuhaha** [tmick0/egg58#3]
Please make choc spacing version.

**Comment by tmick0** [comment]
Hi @nanpuhaha, the current version is already nominally choc spacing (actual footprint 18.5x17.5mm). Do you mean you want tighter tolerances on this, or did you mean you want an MX version?

**Comment by nanpuhaha** [comment]
As I know, choc spacing is [18 x 17mm](https://geekhack.org/index.php?topic=107487.0). I wonder why you decided to make it a bit larger.

**Comment by tmick0** [comment]
When I was initially designing this, I found that actual spacing among choc boards seems to vary up to 1mm from the nominal 18x17. I chose the .5mm larger footprint as to give a full 1mm gap between keycaps. This helps me prevent typos since I have larger fingers, and it also turned out to the provide necessary space to route the traces... However I could probably make the 18x17 work in a version that only supports SMT diodes.

I have just started on a design for an SMT-only version anyway - so, I may as well try to reduce the spacing simultaneously. I'll let you know how it goes :)
