### ISSUE TITLE
Question About jumpers

### ISSUE THREAD

**Issue by cj360** [tmick0/egg58#4]
So I have a pair of sea-micros another pro micro clone and the I2C resistors for a set of egg58. 
![Screenshot (4)cropped](https://github.com/eggsworks/egg58/assets/2075051/b1eafa66-4003-4ed2-aed4-613520436e1d)

Should I be adding a jumper like the red color or just solder the pads like cyan?

**Comment by tmick0** [comment]
The two sets of jumper pads are independent.

The ProMicro/EliteC jumper is about the position of the VBUS/RAW pin, in order to both power the LEDs and provide 5v to the other half of the keyboard. It looks like the Sea-Micro puts it in the same position as the Pro Micro, so you should choose the ProMicro position.

The Serial/I2C jumper selects the data pin which connects to the TRRS socket (PD1 for I2C or PD2 for softserial).

Each jumper should have one outer pad tied to the inner pad:

![image](https://github.com/eggsworks/egg58/assets/978784/4bd41ac1-3f93-4a67-a3b5-53bfc82aad11)

Sorry for the confusion - I'll update the readme with this information when I get a chance.
